= ledgerexport-tax

Application that exports data from ledger to txt. +
It is a register report for a given tax quarter.

== Examples

For Q1, the following files will be generated: +
* reg_<date>_V001_btw_Q1.pdf +
* reg_<date>_V001_btw_januari.pdf +
* reg_<date>_V001_btw_februari.pdf +
* reg_<date>_V001_btw_march.pdf

The export is to txt-files, which are then converted to pdf files. +
This last step is needed, because the accounting software I use, does not accept txt-files.

== Dependencies

* sbcl, since this is a common lisp script. +
* vim, because that is used to transform the txt to pdf.

== Loading

You can start sbcl and execute: +
(push #p"/path/to/dev/ledgerexport-tax/")

followed by a: +
(ql:quickload :ledgerexport-tax)

TODO: Find a better way to do this. I also need to do the push thing everytime, which seems weird to me.

There is also the following to be added to .sblrc: +

++++
;;; The following was added, to allow ql:quickload on own projects.
#+quicklisp
(progn
(pushnew #P"/home/myusername/dev/ledgerexport-tax/"
ql:*local-project-directories*))
++++

This allows starting sbcl and doing

++++
(ql:quickload :ledgerexport-tax)
++++

but it doesn't work for starting as a script with sbcl --noinform --script.
